### PR TITLE
updated user table with profile header and integrated Wanchen code

### PR DESCRIPTION
**Pull request by adoll04**

### CODE REVIEW

**Comment by abbubhai** [comment]
Your code contains only an image file. Are u sure this is changes u have made ?

**Comment by abbubhai** [comment]
Although it doesn't have any conflicts i just want to confirm if that is the only change ?

**Comment by adoll04** [comment]
I did pull request wrong. Please delete

**Comment by abbubhai** [comment]
I m closing the pull request. Plz do a new one.

**Pull request closed without merging**
