### PR TITLE
User activity tracking

### PR DESCRIPTION
**Pull request by jlofshultuno**

### CODE REVIEW

**Comment by jlofshultuno** [comment]
@hcghanta This should be safe to merge. There shouldn't be any migration conflicts. However, you will need to add a column to account_program.program_id and add values to it. There should only be two rows and the Spring 2019 should be 1 and the other would be 2.

**Comment by hcghanta** [comment]
I understood what you are trying to say but even I cannot do changes to the existing model. @Tarun1226 do you think we can integrate these changes to the new heroku app?
@jlofshultuno I see you created new models but I cannot see the migrations file

**Comment by jlofshultuno** [comment]
> I understood what you are trying to say but even I cannot do changes to the existing model. @Tarun1226 do you think we can integrate these changes to the new heroku app?
> @jlofshultuno I see you created new models but I cannot see the migrations file

Hema, I didn't think we were supposed to include the migration files. Should I be including those?

**Comment by Tarun1226** [comment]
> I understood what you are trying to say but even I cannot do changes to the existing model. @Tarun1226 do you think we can integrate these changes to the new heroku app?
> @jlofshultuno I see you created new models but I cannot see the migrations file

Yes, for sure model change can be done in new heroku app and i would be able to integrate it.

**Comment by hcghanta** [comment]
@jlofshultuno Yes we need to have the migrations file that is the reason we are creating a new heroku app since we don't have the initial migration files. If you and @Tarun1226 can finish integrating your code in the new app and finish your unit testing before EOD thursday, I will go ahead and assign it to someone else to do the testing.

**Pull request closed without merging**
